// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OJT_RAG.Repositories.Context;

#nullable disable

namespace OJT_RAG.Repositories.Migrations
{
    [DbContext(typeof(OJTRAGContext))]
    [Migration("20260115121125_AddSemesterCompanyIdAndRelationship")]
    partial class AddSemesterCompanyIdAndRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.ChatRoom", b =>
                {
                    b.Property<long>("ChatRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatRoomId"));

                    b.Property<string>("ChatRoomTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("chat_room_title");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ChatRoomId");

                    b.HasIndex("UserId");

                    b.ToTable("chat_room");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Company", b =>
                {
                    b.Property<long>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CompanyId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("logo_url");

                    b.Property<long?>("MajorId")
                        .HasColumnType("bigint")
                        .HasColumnName("majorid");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_at");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("CompanyId");

                    b.HasIndex("MajorId");

                    b.ToTable("company");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Companydocument", b =>
                {
                    b.Property<long>("CompanydocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("companydocument_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CompanydocumentId"));

                    b.Property<string>("FileUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_url");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<long?>("SemesterCompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("semester_company_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<long?>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.HasKey("CompanydocumentId");

                    b.HasIndex("SemesterCompanyId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("companydocument");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Companydocumenttag", b =>
                {
                    b.Property<long>("CompanyDocumentTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("companydocumenttag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CompanyDocumentTagId"));

                    b.Property<long>("CompanyDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("companydocument_id");

                    b.Property<long>("DocumentTagId")
                        .HasColumnType("bigint")
                        .HasColumnName("documenttag_id");

                    b.HasKey("CompanyDocumentTagId");

                    b.HasIndex("CompanyDocumentId");

                    b.HasIndex("DocumentTagId");

                    b.ToTable("companydocumenttag");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Documenttag", b =>
                {
                    b.Property<long>("DocumenttagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("documenttag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumenttagId"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("DocumenttagId");

                    b.ToTable("documenttag");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Finalreport", b =>
                {
                    b.Property<long>("FinalreportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("finalreport_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FinalreportId"));

                    b.Property<string>("CompanyEvaluator")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_evaluator");

                    b.Property<string>("CompanyFeedback")
                        .HasColumnType("text")
                        .HasColumnName("company_feedback");

                    b.Property<int?>("CompanyRating")
                        .HasColumnType("integer")
                        .HasColumnName("company_rating");

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<long?>("JobPositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_position_id");

                    b.Property<long?>("SemesterId")
                        .HasColumnType("bigint")
                        .HasColumnName("semester_id");

                    b.Property<string>("StudentReportFile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("student_report_file");

                    b.Property<string>("StudentReportText")
                        .HasColumnType("text")
                        .HasColumnName("student_report_text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submitted_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("FinalreportId");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("UserId");

                    b.ToTable("finalreport");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.JobBookmark", b =>
                {
                    b.Property<long>("JobBookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("job_bookmark_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JobBookmarkId"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<long?>("JobPositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_position_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("JobBookmarkId");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("UserId");

                    b.ToTable("job_bookmark");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.JobDescription", b =>
                {
                    b.Property<long>("JobDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("job_description_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JobDescriptionId"));

                    b.Property<int?>("AppliedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("applied_quantity");

                    b.Property<int?>("HireQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("hire_quantity");

                    b.Property<string>("JobDescription1")
                        .HasColumnType("text")
                        .HasColumnName("job_description");

                    b.Property<long?>("JobPositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_position_id");

                    b.HasKey("JobDescriptionId");

                    b.HasIndex("JobPositionId");

                    b.ToTable("job_description");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.JobPosition", b =>
                {
                    b.Property<long>("JobPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("job_position_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JobPositionId"));

                    b.Property<string>("Benefit")
                        .HasColumnType("text")
                        .HasColumnName("benefit");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("job_title");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<long?>("MajorId")
                        .HasColumnType("bigint")
                        .HasColumnName("major_id");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("SalaryRange")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("salary_range");

                    b.Property<long?>("SemesterCompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("semester_company_id");

                    b.Property<long?>("SemesterId")
                        .HasColumnType("bigint")
                        .HasColumnName("semester_id");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("JobPositionId");

                    b.HasIndex("MajorId");

                    b.HasIndex("SemesterCompanyId");

                    b.HasIndex("SemesterId");

                    b.ToTable("job_position");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.JobTitleOverview", b =>
                {
                    b.Property<long>("JobTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("job_title_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JobTitleId"));

                    b.Property<string>("JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("job_title");

                    b.Property<int?>("PositionAmount")
                        .HasColumnType("integer")
                        .HasColumnName("position_amount");

                    b.HasKey("JobTitleId");

                    b.ToTable("job_title_overview");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Major", b =>
                {
                    b.Property<long>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("major_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MajorId"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("MajorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("major_code");

                    b.Property<string>("MajorTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("major_title");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("MajorId");

                    b.ToTable("major");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<long?>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("FromAi")
                        .HasColumnType("boolean")
                        .HasColumnName("from_ai");

                    b.Property<string>("Sources")
                        .HasColumnType("text")
                        .HasColumnName("sources");

                    b.Property<bool?>("Useful")
                        .HasColumnType("boolean")
                        .HasColumnName("useful");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatRoomId");

                    b.ToTable("message");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Ojtdocument", b =>
                {
                    b.Property<long>("OjtdocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ojtdocument_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OjtdocumentId"));

                    b.Property<string>("FileUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_url");

                    b.Property<bool?>("IsGeneral")
                        .HasColumnType("boolean")
                        .HasColumnName("is_general");

                    b.Property<long?>("SemesterId")
                        .HasColumnType("bigint")
                        .HasColumnName("semester_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<long?>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.HasKey("OjtdocumentId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("ojtdocument");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Ojtdocumenttag", b =>
                {
                    b.Property<long>("OjtDocumentTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ojtdocumenttag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OjtDocumentTagId"));

                    b.Property<long>("DocumentTagId")
                        .HasColumnType("bigint")
                        .HasColumnName("documenttag_id");

                    b.Property<long>("OjtDocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("ojtdocument_id");

                    b.HasKey("OjtDocumentTagId");

                    b.HasIndex("DocumentTagId");

                    b.HasIndex("OjtDocumentId");

                    b.ToTable("ojtdocumenttag");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Semester", b =>
                {
                    b.Property<long>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("semester_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SemesterId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("SemesterId");

                    b.ToTable("semester");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.SemesterCompany", b =>
                {
                    b.Property<long>("SemesterCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("semester_company_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SemesterCompanyId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<long?>("SemesterId")
                        .HasColumnType("bigint")
                        .HasColumnName("semester_id");

                    b.HasKey("SemesterCompanyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SemesterId");

                    b.ToTable("semester_company");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatar_url");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cv_url");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<long?>("MajorId")
                        .HasColumnType("bigint")
                        .HasColumnName("major_id");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("student_code");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MajorId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.UserChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_chat_message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint")
                        .HasColumnName("receiver_id");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.ToTable("user_chat_message");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.ChatRoom", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.User", "User")
                        .WithMany("ChatRooms")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Company", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.Major", "Major")
                        .WithMany("Companies")
                        .HasForeignKey("MajorId");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Companydocument", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.SemesterCompany", "SemesterCompany")
                        .WithMany("Companydocuments")
                        .HasForeignKey("SemesterCompanyId");

                    b.HasOne("OJT_RAG.Repositories.Entities.User", "UploadedByNavigation")
                        .WithMany("Companydocuments")
                        .HasForeignKey("UploadedBy");

                    b.Navigation("SemesterCompany");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Companydocumenttag", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.Companydocument", "CompanyDocument")
                        .WithMany("CompanyDocumentTags")
                        .HasForeignKey("CompanyDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJT_RAG.Repositories.Entities.Documenttag", "DocumentTag")
                        .WithMany("CompanyDocumentTags")
                        .HasForeignKey("DocumentTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyDocument");

                    b.Navigation("DocumentTag");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Finalreport", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.JobPosition", "JobPosition")
                        .WithMany("Finalreports")
                        .HasForeignKey("JobPositionId");

                    b.HasOne("OJT_RAG.Repositories.Entities.Semester", "Semester")
                        .WithMany("Finalreports")
                        .HasForeignKey("SemesterId");

                    b.HasOne("OJT_RAG.Repositories.Entities.User", "User")
                        .WithMany("Finalreports")
                        .HasForeignKey("UserId");

                    b.Navigation("JobPosition");

                    b.Navigation("Semester");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.JobBookmark", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.JobPosition", "JobPosition")
                        .WithMany("JobBookmarks")
                        .HasForeignKey("JobPositionId");

                    b.HasOne("OJT_RAG.Repositories.Entities.User", "User")
                        .WithMany("JobBookmarks")
                        .HasForeignKey("UserId");

                    b.Navigation("JobPosition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.JobDescription", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.JobPosition", "JobPosition")
                        .WithMany("JobDescriptions")
                        .HasForeignKey("JobPositionId");

                    b.Navigation("JobPosition");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.JobPosition", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.Major", "Major")
                        .WithMany("JobPositions")
                        .HasForeignKey("MajorId");

                    b.HasOne("OJT_RAG.Repositories.Entities.SemesterCompany", "SemesterCompany")
                        .WithMany("JobPositions")
                        .HasForeignKey("SemesterCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OJT_RAG.Repositories.Entities.Semester", "Semester")
                        .WithMany("JobPositions")
                        .HasForeignKey("SemesterId");

                    b.Navigation("Major");

                    b.Navigation("Semester");

                    b.Navigation("SemesterCompany");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Message", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId");

                    b.Navigation("ChatRoom");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Ojtdocument", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.Semester", "Semester")
                        .WithMany("Ojtdocuments")
                        .HasForeignKey("SemesterId");

                    b.HasOne("OJT_RAG.Repositories.Entities.User", "UploadedByNavigation")
                        .WithMany("Ojtdocuments")
                        .HasForeignKey("UploadedBy");

                    b.Navigation("Semester");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Ojtdocumenttag", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.Documenttag", "DocumentTag")
                        .WithMany("OjtDocumentTags")
                        .HasForeignKey("DocumentTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OJT_RAG.Repositories.Entities.Ojtdocument", "OjtDocument")
                        .WithMany("OjtDocumentTags")
                        .HasForeignKey("OjtDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentTag");

                    b.Navigation("OjtDocument");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.SemesterCompany", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.Company", "Company")
                        .WithMany("SemesterCompanies")
                        .HasForeignKey("CompanyId");

                    b.HasOne("OJT_RAG.Repositories.Entities.Semester", "Semester")
                        .WithMany("SemesterCompanies")
                        .HasForeignKey("SemesterId");

                    b.Navigation("Company");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.User", b =>
                {
                    b.HasOne("OJT_RAG.Repositories.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.HasOne("OJT_RAG.Repositories.Entities.Major", "Major")
                        .WithMany("Users")
                        .HasForeignKey("MajorId");

                    b.Navigation("Company");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Company", b =>
                {
                    b.Navigation("SemesterCompanies");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Companydocument", b =>
                {
                    b.Navigation("CompanyDocumentTags");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Documenttag", b =>
                {
                    b.Navigation("CompanyDocumentTags");

                    b.Navigation("OjtDocumentTags");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.JobPosition", b =>
                {
                    b.Navigation("Finalreports");

                    b.Navigation("JobBookmarks");

                    b.Navigation("JobDescriptions");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Major", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("JobPositions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Ojtdocument", b =>
                {
                    b.Navigation("OjtDocumentTags");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.Semester", b =>
                {
                    b.Navigation("Finalreports");

                    b.Navigation("JobPositions");

                    b.Navigation("Ojtdocuments");

                    b.Navigation("SemesterCompanies");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.SemesterCompany", b =>
                {
                    b.Navigation("Companydocuments");

                    b.Navigation("JobPositions");
                });

            modelBuilder.Entity("OJT_RAG.Repositories.Entities.User", b =>
                {
                    b.Navigation("ChatRooms");

                    b.Navigation("Companydocuments");

                    b.Navigation("Finalreports");

                    b.Navigation("JobBookmarks");

                    b.Navigation("Ojtdocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
